apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "krateo-bff.fullname" . }}
  labels:
    {{- include "krateo-bff.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
# krateo bff crds
- apiGroups:
  - widgets.ui.krateo.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - layout.ui.krateo.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - core.krateo.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps.krateo.io
  resources:
  - '*'
  verbs:
  - '*'
