apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
data:
  KRATEO_BFF_DEBUG: "{{ .Values.KRATEO_BFF_DEBUG }}"
  KRATEO_BFF_PORT: "{{ .Values.KRATEO_BFF_PORT }}"
  AUTHN_STORE_NAMESPACE: {{ .Values.AUTHN_STORE_NAMESPACE }}
 