apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krateo-bff.fullname" . }}
  labels:
    {{- include "krateo-bff.labels" . | nindent 4 }}
data:
  KRATEO_BFF_DEBUG: "{{ .Values.env.KRATEO_BFF_DEBUG }}"
  KRATEO_BFF_PORT: "{{ .Values.service.port }}"
  AUTHN_STORE_NAMESPACE: {{ .Values.env.AUTHN_STORE_NAMESPACE }}
